# Generated by Django 4.2.7 on 2026-04-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('daily_calories', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('carbs', 'Carbohydrates'), ('fat', 'Healthy Fats'), ('vegetable', 'Vegetables'), ('fruit', 'Fruits'), ('dairy', 'Dairy'), ('supplement', 'Supplements')], max_length=15)),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField(default=0)),
                ('carbs_per_100g', models.FloatField(default=0)),
                ('fat_per_100g', models.FloatField(default=0)),
                ('fiber_per_100g', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], max_length=15)),
                ('amount_g', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('prep_time_minutes', models.PositiveIntegerField(default=15)),
                ('instructions', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/')),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_g', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('endurance', 'Endurance')], max_length=20)),
                ('daily_calories', models.PositiveIntegerField(default=2000)),
                ('protein_g', models.PositiveIntegerField(default=150)),
                ('carbs_g', models.PositiveIntegerField(default=200)),
                ('fat_g', models.PositiveIntegerField(default=65)),
                ('water_ml', models.PositiveIntegerField(default=2500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
