# Generated by Django 4.2.7 on 2026-04-18 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiongoal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diet.fooditem'),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='diet.meal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='food_items',
            field=models.ManyToManyField(through='diet.MealIngredient', to='diet.fooditem'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diet.fooditem'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_diet_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diet_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietday',
            name='meals',
            field=models.ManyToManyField(blank=True, to='diet.meal'),
        ),
        migrations.AddField(
            model_name='dietday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='diet.dietplan'),
        ),
        migrations.AlterUniqueTogether(
            name='dietday',
            unique_together={('plan', 'day_number')},
        ),
    ]
